# Site
title:              MITERS
description:        "MIT Electronics Research Society"
url:            "https://miters.github.io"
logo:           /assets/icon/apple-touch-icon.png

# defaults:
# - scope:
#     path: ''
#     type: posts
#   values:
#     permalink: "/blog/:title/"
#     layout: post
#     author:

# Author
author:
  name:         MITERS
  url:          https://miters.github.io
  email:        miters@mit.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

exclude: ['README.md', 'LICENSE.md', 'Gemfile.lock', 'Gemfile']